---
- hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - akeyless.secrets_management

  tasks:
    - name: Fetch secret from Akeyless
      akeyless_secret:
        name: "/1-static-secret/FirstSecret"
        type: static
      register: akeyless_result

    - name: Print the secret
      debug:
        msg: "Secret value: {{ akeyless_result.value }}"
