---
- hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - akeyless.secrets_management

  tasks:

    - name: Get temp token using api_key auth method
      login:
        akeyless_api_url: 'https://api.akeyless.io'
        access_type: 'jwt'
        access_id: 'p-y5bae7zhmim1om'
        jwt: '<jwt value>'
      register: auth_res
    - name: Fetch secret from Akeyless
      get_static_secret_value:
        akeyless_api_url: 'https://api.akeyless.io'
        names: '/1-static-secret/FirstSecret'
        token: '{{ auth_res.data.token }}'
      register: response

    - name: Display the results
      debug:
        msg: "Secret Value: {{ response.data }}"
